# just a regular docker-compose.yml file
version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/test
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - acme
    restart: unless-stopped

volumes:
  postgres:

networks:
  acme:
    driver: bridge
